### ISSUE TITLE
[MacOS] Find options not working in Android Studio after settings installation

### ISSUE THREAD

**Issue by professeurburp** [galonga/Monokai-Android-Studio#1]
I recently installed the settings jar on my Android Studio, and while syntaxic coloration is perfect, I'm facing a seriously annoying bug.

Since the Monokai settings installation, Find options are not working properly any more.

The in-file search (Cmd + F) command shows the bar at the top of the file, but does not intercept key strokes, sometimes leading to a timeout, and text is finally (after some long delay, like 10-15 seconds) written directly in the source code file.

Also, Find all occurrences (Cmd + Maj + F), does not react any more, and does nothing.

Other search options (Find usages, etc...) seem to behave correctly.

MacOS: 10.14.2
Android Studio: 3.3

**Comment by professeurburp** [comment]
A quick follow up on this.

First, I noticed there was a problem with keymap, it seemed both 'Find in file' and 'Find in Patch' were assigned the same Cmd + F shortcut.

When replacing 'Find in path' shortcut with Cmd + MAJ + F, now the 'Find in file' search textbox reacts to keystrokes, except with a really long delay sometimes causing the following exception to be launched by Android Studio:

`java.lang.RuntimeException: Typeahead timeout is exceeded: 10001
	at com.intellij.ide.IdeEventQueue.lambda$isTypeaheadTimeoutExceeded$18(IdeEventQueue.java:1186)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:394)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`
